In [1]:
import pandas as pd
from mlxtend.preprocessing import OnehotTransactions
from mlxtend.frequent_patterns import apriori


dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

oht = OnehotTransactions()
oht_ary = oht.fit(dataset).transform(dataset)
df = pd.DataFrame(oht_ary, columns=oht.columns_)
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

frequent_itemsets

    support                     itemsets
0       0.8                       [Eggs]
1       1.0               [Kidney Beans]
2       0.6                       [Milk]
3       0.6                      [Onion]
4       0.6                     [Yogurt]
5       0.8         [Eggs, Kidney Beans]
6       0.6                [Eggs, Onion]
7       0.6         [Kidney Beans, Milk]
8       0.6        [Kidney Beans, Onion]
9       0.6       [Kidney Beans, Yogurt]
10      0.6  [Eggs, Kidney Beans, Onion]

In [2]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

              antecedants            consequents  support  confidence  lift
0                  (Eggs)                (Onion)      0.8        0.75  1.25
1                 (Onion)                 (Eggs)      0.6        1.00  1.25
2                 (Onion)         (Kidney Beans)      0.6        1.00  1.00
3                (Yogurt)         (Kidney Beans)      0.6        1.00  1.00
4                  (Eggs)         (Kidney Beans)      0.8        1.00  1.00
5          (Kidney Beans)                 (Eggs)      1.0        0.80  1.00
6                  (Milk)         (Kidney Beans)      0.6        1.00  1.00
7    (Eggs, Kidney Beans)                (Onion)      0.8        0.75  1.25
8           (Eggs, Onion)         (Kidney Beans)      0.6        1.00  1.00
9   (Kidney Beans, Onion)                 (Eggs)      0.6        1.00  1.25
10                 (Eggs)  (Kidney Beans, Onion)      0.8        0.75  1.25
11                (Onion)   (Eggs, Kidney Beans)      0.6        1.00  1.25

In [3]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules

             antecedants            consequents  support  confidence  lift
0                 (Eggs)                (Onion)      0.8        0.75  1.25
1                (Onion)                 (Eggs)      0.6        1.00  1.25
2   (Eggs, Kidney Beans)                (Onion)      0.8        0.75  1.25
3  (Kidney Beans, Onion)                 (Eggs)      0.6        1.00  1.25
4                 (Eggs)  (Kidney Beans, Onion)      0.8        0.75  1.25
5                (Onion)   (Eggs, Kidney Beans)      0.6        1.00  1.25

In [4]:
rules["antecedant_len"] = rules["antecedants"].apply(lambda x: len(x))
rules

,antecedants,consequents,support,confidence,lift,antecedant_len
0,(Eggs),(Onion),0.8,0.75,1.25,1
1,(Onion),(Eggs),0.6,1.00,1.25,1
2,"(Eggs, Kidney Beans)",(Onion),0.8,0.75,1.25,2
3,"(Kidney Beans, Onion)",(Eggs),0.6,1.00,1.25,2
4,(Eggs),"(Kidney Beans, Onion)",0.8,0.75,1.25,1
5,(Onion),"(Eggs, Kidney Beans)",0.6,1.00,1.25,1

In [5]:
rules[ (rules['antecedant_len'] >= 2) &
       (rules['confidence'] > 0.75) &
       (rules['lift'] > 1.2) ]

,antecedants,consequents,support,confidence,lift,antecedant_len
3,"(Kidney Beans, Onion)",(Eggs),0.6,1.0,1.25,2